### PR TITLE
Add a knobby pipe type.

### PR DESCRIPTION
**Pull request by parkercoates**
This one is interesting in that it's the only pattern that uses a different character for each cell type. Lines going up look slightly difference than lines going down, etc. Plus it kinda looks like a worm.

Of course I understand if you want to limit the number of pipe types now that custom types are supported.

### CODE REVIEW

**Comment by Foggalong** [comment]
Can you post a screenshot of what this is supposed to look like? I'm getting very different results on different machines

**Comment by parkercoates** [comment]
This is what it is intended to look like:

pipes sh-knobby

Maybe the font on one of your machines is missing these narrow-to-wide box drawing characters? I assumed they'd be as well supported as the rounded box drawing characters, but I could definitely be wrong.

**Comment by Foggalong** [comment]
That looks really nice yeah! On my main computer though (which iirc is using ubuntu-mono) the knobble looks more like this █. I'll try and get a better screenshot when I'm at keyboard again.

**Comment by Foggalong** [comment]
Just as a note, the knobby type needs adding to the README too. For the image just added a cropped version of the one above since that seems to lookpretty similar :)

**Comment by Foggalong** [comment]
This is now working fine on my home computer so I'm not sure what changed :/ anyway, thanks for the addition! Don't worry about the README I'll sort that stuff out

**Comment by parkercoates** [comment]
Thanks!

**Pull request merged**
